---

- name: Install Docker
  hosts: server
  become: true
  tasks:
  - name: Install Docker
    apt:
      pkg: docker
  - name: Install Docker-compose
    apt:
      pkg: docker-compose
  - name: Ensure Docker is running
    systemd:
      name: docker
      state: started
  - name: Install docker python module
    pip:
      name: 
      - docker
      - docker-compose


- name: Add docker user to docker group
  hosts: server
  become: yes
  tasks:
  - name: add user to docker group
    user: 
      name: azureuser
      groups: docker
      append: true
  - name: Reset server connection # we reset the server comnnection to ensure new user created is added to the docker group. 
    meta: reset_connection

- name: Test docker pull
  hosts: server
  tasks:
  - name: pull Redis
    docker_image:
      name: redis 
      source: pull 

- name: Start docker containers
  hosts: server
  vars_files: # set variable location to store secret 
    - project-vars 
  tasks: 
  - name: Copy docker compose 
    copy: 
      src: /home/dev-test/docker-compose.yaml
      dest: /home/azureuser/docker-compose.yaml
  - name: Docker login
    docker_login: 
      registry_url: https://index.docker.io/v1/
      username: cyb3rjay@outlook.com
      password: "{{docker_password}}"
  - name: Start docker container from compose 
    docker_compose: 
      project_src: /home/azureuser # identify the docker compose file location 
      state: present # docker compose up 
