---

- name: Install Docker 
  hosts: server
  become: true
  tasks: 
  - name: Install Docker 
    apt: 
      pkg: docker
    
- name: Install Docker-compose
  hosts: server
  become: true
  tasks: 
  - name: Install Docker-compose
    apt: 
      pkg: docker-compose-plugin