---
- name: install node and npm on server 
  hosts: servers
  tasks: 
  - name: Update apt and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install node and npm
    become: true
    apt: 
      pkg: 
        - nodejs
        - npm

- name: deploy node js application
  hosts: servers
  tasks: 
  - name: unpack the nodejs tar file
    unarchive: 
      src: /home/demo/nodejs-app/nodejs-app-1.0.0.tgz
      dest: /home/azureuser/
  - name: npm install dependencies 
    npm: 
      path: /home/azureuser/package
  - name: start the application
    command: 
      chdir: /home/azureuser/package/app
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running 
    shell: ps aux | grep node 
    register: app_status
  - debug: msg={{app_status.stdout_lines}}
    
