---

- name: configuring nginx web servers
  hosts: server
  tasks: 
  - name: install nginx web servers
    apt: 
      name: install nginx 
      state: latest
  - name: start nginx web servers
    service:
      name: nginx
      state: started