---

- name: configuring nginx web servers
  hosts: server
  tasks: 
  - name: install nginx web servers
    become: true
    pkg: 
      - name: nginx 
      - state: latest
  - name: start nginx web servers
    service:
      name: nginx
      state: started
